spring.application.name=financeai
ml.service.url=http://localhost:8000
spring.datasource.url=jdbc:h2:file:./data/financeai
logging.level.org.springframework.web.client.RestClient=DEBUG
spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.path=/documentacion
springdoc.api-docs.path=/api/documentacion