spring.application.name=financeai
server.port=${PORT:8080}
ml.service.url=${ML_SERVICE_URL:http://localhost:8000}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
spring.datasource.url=jdbc:h2:file:./data/financeai
logging.level.org.springframework.web.client.RestClient=DEBUG
spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.path=/documentacion
springdoc.api-docs.path=/api/documentacion
